# Site settings
title: Pixelated Project
email: yet@to.be.created
description: "Secure OSS email solution"
baseurl: ""
url: "http://pixelated-project.github.io/"
twitter_username: pixelatedteam
github_username:  pixelated-project

# Build settings
markdown: kramdown
